# the default config file
[game]
fps = 60.0
logfile = "app.log"
graphics = true

[camera]
zoom = 3.0
bottom_margin_fraction = 0.08

[player]
gravity_px = 300.0
jump_speed_px = 120.0
death_pause_seconds = 3.0

[visualizer]
enabled = true
